### ISSUE TITLE
An error occurs if "Generate native Segwit" is selected when requesting the payment

### ISSUE THREAD

**Issue by hardwarewise** [SINOVATEblockchain/SIN-core#12]
An error occurs if "Generate native Segwit" is selected when requesting the payment
![image](https://user-images.githubusercontent.com/47283265/55067677-2e5f7a80-5091-11e9-9250-9129d318cc89.png)

**Comment by giaki3003** [comment]
Could you provide any extra informationif possible? Platform/Binary version/OS
