### ISSUE TITLE
Output index not equal

### ISSUE THREAD

**Issue by cyberd3vil** [SINOVATEblockchain/SIN-core#126]
In Windows wallet, Transaction tab, when selecting `Show transaction details` or double clicking a transaction to get details, **sometimes**, the `output index` shown, is not correct. This may be misleading for those creating a new infinitynode.

See screenshots below, taken during infinitynode creation on testnet.
The same happening with mainnet wallet. Got the same issue on versions:
- SIN.version.v0.17.1.5-ec78b3b.WIN-64-bit
- SIN.version.v0.17.1.4-99419f9.Win.64-bit

![img_01](https://user-images.githubusercontent.com/20667441/73523173-8c27c600-440a-11ea-9043-809c8e07f529.PNG)

![img_02](https://user-images.githubusercontent.com/20667441/73523178-8fbb4d00-440a-11ea-9942-b78b7357f3f0.PNG)

![img_03](https://user-images.githubusercontent.com/20667441/73523186-921da700-440a-11ea-8077-1fe1bd70c0b6.PNG)

**Comment by giaki3003** [comment]
The transaction has two vouts, so you get the same hash pointing at vout 1, and pointing at vout 2. Its how the blockchain works :)
