### ISSUE TITLE
evolution of infinityburnfund

### ISSUE THREAD

**Issue by crptec** [SINOVATEblockchain/SIN-core#35]
It would be cool if you could modify infinityburnfund with selection of address with input from console - ie infinityburnfund "youraddresstoburnfrom" 1000

 I guess if you will have that you can improve autosin with even more automation:
1. First you suggest the address to send amount to burn to the user
2. After user sends this amount you can processed with existing console commands to setup InfinityNode - burnfund, send collateral, outputs etc

from: @Vaulter

**Comment by Cryplander** [comment]
Added and will be present in the upcoming release.
