### ISSUE TITLE
Sinovate Wallet Failed to Load LockReward cache

### ISSUE THREAD

**Issue by jpower1196** [SINOVATEblockchain/SIN-core#405]
Does anyone know how to fix this problem? I have a copy of my wallet data of when it was originally created and that my masternode is linked to.

**Comment by Cryplander** [comment]
Hello. 
Close the wallet

Delete everything except wallet.dat.

Copy the files extracted from the bootstrap.zip file to the SIN directory.

https://github.com/SINOVATEblockchain/SIN-core/releases/download/v1.0.0.2/bootstrap.zip

Start the wallet.

You can have detailed information on this guide.

https://docs.sinovate.io/#/wallet_upgrade
