### ISSUE TITLE
Sinovate Node not updating

### ISSUE THREAD

**Issue by jpower1196** [SINOVATEblockchain/SIN-core#406]
My last logged deposit from my node is from July 9th, it's currently august 29th, is there anyway to see my actual balance of SIN? Another question say I have a wrong wallet back up, is there anyway to actually get my actual coins accumulated through the last month? Every 2 days or so I have notice that I accumulate about 560 coins. Since July 9th, I have lost out on an estimated 14,280 sin. If anyone could help me on this issue I'd be much appreciative, I work 3 jobs and maintaining this node is about to be a 4th! So much for passive income!

[
![Screen Shot 2021-08-29 at 12 19 18 AM](https://user-images.githubusercontent.com/87539377/131238274-aff47190-0e9b-4847-b362-0f0270e411dd.png)
](url)

**Comment by hardwarewise** [comment]
Hi; 
If you are using the setUP service,
It would be better to open a support ticket at https://setup.sinovate.io/. Otherwise, we welcome you to our Discord channel at https://discordapp.com/invite/CWbnW5y.

**Because it is not right to discuss your personal information in this environment.**
