### ISSUE TITLE
Prune mode is incompatible with -txindex

### ISSUE THREAD

**Issue by Borix668** [SINOVATEblockchain/SIN-core#55]

**Comment by giaki3003** [comment]
Pruning will disable indexing of any sorts.

**Comment by installer1983** [comment]
how did you fix it???

**Comment by Borix668** [comment]
I did not fix it, just quit

Sent from Mail for Windows 110

**Comment by installer1983** [comment]
every time i have message when i start sin qt Prune mode is incompatible with -txindex    i dont know what to do

**Comment by Cryplander** [comment]
Add prune=0 in  your sin.conf file and restart the wallet.
