### ISSUE TITLE
suqa transform sin ??

### ISSUE THREAD

**Issue by JHong111** [SINOVATEblockchain/SIN-core#56]
How can I convert suqa to sin? 
Import wallet.dat or comfortably send all my coins from my old SUQA address to the new SIN core wallet address?? 
please help me ,thanks!

**Comment by pallas1** [comment]
You can't send coins using the old suqa wallet, as it is now on a dead chain.
Please come to discord for support and tutorials.

**Comment by JHong111** [comment]
> 你不能使用旧的suqa钱包发送硬币，因为它现在处于死链状态。
> 请来支持和教程不和。



> You can't send coins using the old suqa wallet, as it is now on a dead chain.
> Please come to discord for support and tutorials.

Can I use suqa's wallet.dat directly in the sin wallet? What is the entry address for discord?

**Comment by giaki3003** [comment]
Please send a message to our Discord moderators about your situation. Thanks
