### ISSUE TITLE
sin-qt: error while loading shared libraries: libboost_system.so.1.65.1

### ISSUE THREAD

**Issue by Shekelme** [SINOVATEblockchain/SIN-core#57]
So I downloaded INFINITYNODESv1.02- d24bd6b-0.17.1 Linux wallet. But I can't start it under Ubuntu 16.04.1. The error message is:

`./sin-qt: error while loading shared libraries: libboost_system.so.1.65.1: cannot open shared object file: No such file or directory`

**Comment by pallas1** [comment]
You can either upgrade to 18.04 or compile the wallet yourself.
I'm planning to also provide a 16.04 binary but, honestly, 18.04 LTS is more than 1 year old!
