### ISSUE TITLE
qt-wallet laggy

### ISSUE THREAD

**Issue by cyberd3vil** [SINOVATEblockchain/SIN-core#60]
OS: Win10 Pro

Wallet version: 
SIN.version.v0.17.1.0-78500e8.64-bit
SIN.version.WInX64.v0.17.1.0-d24bd6b.64-bit

The qt-wallet is really laggy, responding to clicks within 3 to 6 seconds. CPU usage over 40%
Same problem on 2 different PC (cpu i5 with 16 GB RAM and cpu i7 with 32GB RAM).

If wallet.dat deleted (address inside with +1.000 transactions) and new wallet.dat created, the qt-wallet has no lags at all.

Trying to use a new wallet.dat and after importing private key, the qt-wallet is lagging again.

**Comment by pallas1** [comment]
As a quick workaround, just send coins to a new address which is in another wallet.dat

**Comment by 008** [comment]
thats not that issue, i know, can we set to 256 to speed up net sync a little ?
MAX_BLOCKS_IN_TRANSIT_PER_PEER = 128
validation header line 92
