### ISSUE TITLE
x25x issue

### ISSUE THREAD

**Issue by globaltoken** [SINOVATEblockchain/SIN-core#61]
Hi,

I think this isn't wanted, in hash.h, you hash this:

`   sph_whirlpool_init(&ctx_whirlpool);
    sph_whirlpool (&ctx_whirlpool, static_cast<const void*>(&hash[13]), 64);
    sph_whirlpool_close(&ctx_whirlpool, static_cast<void*>(&hash[14]));

    sph_sha512_init(&ctx_sha2);
    sph_sha512 (&ctx_sha2, static_cast<const void*>(&hash[14]), 64);
    sph_sha512_close(&ctx_sha2, static_cast<void*>(&hash[15]));

    unsigned char temp[SWIFFTX_OUTPUT_BLOCK_SIZE] = {0};
    InitializeSWIFFTX();
    ComputeSingleSWIFFTX((unsigned char*)&hash[12], temp, false);

    memcpy((unsigned char*)&hash[16], temp, 64);
    sph_haval256_5_init(&ctx_haval);
    sph_haval256_5 (&ctx_haval, static_cast<const void*>(&hash[16]), 64);
    sph_haval256_5_close(&ctx_haval, static_cast<void*>(&hash[17]));
`
ComputeSingleSWIFFTX hashes the input of hash12, why hash 12, if you are already at hash 15?

Cheers.

**Comment by pallas1** [comment]
Because input of swifftx is not 64 bytes, but 256.

**Comment by globaltoken** [comment]
@pallas1 I mean the input, look (unsigned char*)&hash[12]

**Comment by pallas1** [comment]
It spans the outputs of the previous 4 algos, so starts at 12 up to 15: 64 * 4 = 256.
See the whitepaper.

**Comment by globaltoken** [comment]
@pallas1 Ah yeah, I got that now! Thanks for the explanation :)

**Comment by globaltoken** [comment]
@pallas1 But another question: is x25x now activated for mainnet?

**Comment by pallas1** [comment]
Yes, it has been for a few days now.
