### ISSUE TITLE
Warn about past backups when encrypting

### ISSUE THREAD

**Issue by pallas1** [SINOVATEblockchain/SIN-core#68]
When encrypting the wallet, the user is warned about loosing the coins if the passphrase is lost, but he's not warned about the past wallet backups, which of course are not encrypted and so not protected. You'd say this is obvious, but it may be less for some, especially if some automatic backups have been made by the wallet. In this case, very often the user doesn't know of the existance of those, possibly unencrypted, backups.
I suggest an addition to the encryption warning, something like "Also, keep in mind the wallet backups you made before encrypting are not protected; look into your datadir to check for automatic backups as well.".

**Comment by hardwarewise** [comment]
![image](https://user-images.githubusercontent.com/47283265/96027638-d352cb80-0e60-11eb-9609-e3182001063a.png)
Thanks for the tip. 
[https://github.com/SINOVATEblockchain/SIN-core/pull/290](url)
