### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by AlexisMinerscience** [SINOVATEblockchain/SIN-core#74]
Hello!
I have Ubuntu 16.04.6 Server. 
I am confused to install a wallet, I do everything as in “build-unix.md”:
   1)   ./contrib/install_db4.sh `pwd`
   2)   ./autogen.sh
   3)   ./configure BDB_LIBS="-L${BDB_PREFIX}/lib -ldb_cxx-4.8" BDB_CFLAGS="-I${BDB_PREFIX}/include"
   4)   make

After compilation in the directory "/SIN-core/src" there are no files to run "sind" or "sin-cli".

Did I do something wrong or files in another directory?

**Comment by AlexisMinerscience** [comment]
> Hello!
> I have Ubuntu 16.04.6 Server.
> I am confused to install a wallet, I do everything as in “build-unix.md”:
> 
> 1. ./contrib/install_db4.sh `pwd`
> 2. ./autogen.sh
> 3. ./configure BDB_LIBS="-L${BDB_PREFIX}/lib -ldb_cxx-4.8" BDB_CFLAGS="-I${BDB_PREFIX}/include"
> 4. make
> 
> After compilation in the directory "/SIN-core/src" there are no files to run "sind" or "sin-cli".
> 
> Did I do something wrong or files in another directory?

**Comment by 008** [comment]
Please use pre-recompiled version https://github.com/SINOVATEblockchain/SIN-core/releases
Sooner or later we will stop support Ubuntu 16 at all, so lets think about move to Ubuntu 18 today.
