### ISSUE TITLE
conflicted with a transaction with 1 confirmations

### ISSUE THREAD

**Issue by ArturChek** [SINOVATEblockchain/SIN-core#87]
I am having random behavior sending the same amount of SIN coins. And for some transactions, I am observing the **conflicted** status.
I cant send available balance, and some times I cant send the same amount that previously was sent successfully.
And I can't understand what I am doing wrong.
I always use the recommended fee.
Can anybody explain what the cause of that issue?

I use client v0.17.1.0-60141a3.

Thanks!

**Comment by piero-orsoni** [comment]
Try this: https://github.com/SINOVATEblockchain/SIN-core/releases/download/v1.02-d24bd6b/guideforoldSUQAcoinsconflict.pdf

**Comment by pallas1** [comment]
Try: https://github.com/SINOVATEblockchain/SIN-core/releases/download/v1.02-d24bd6b/guideforoldSUQAcoinsconflict.pdf

**Comment by ArturChek** [comment]
@pallas1 Thanks, that works!
